//! 依赖解析与版本锁定
//!
//! 生成各语言的依赖配置文件：
//! - Cargo.toml (Rust)
//! - package.json (TypeScript/JS)
//! - requirements.txt / pyproject.toml (Python)
//! - go.mod (Go)
//! - pom.xml / build.gradle (Java)
//! - Package.swift (Swift)

use crate::error::Result;

#[derive(Debug, Clone)]
pub struct Dependency {
    pub name: String,
    pub version: String,
    pub dev: bool,
    pub optional: bool,
    pub description: &'static str,
}

#[derive(Debug, Clone)]
pub struct DependencyFile {
    pub filename: &'static str,
    pub content: String,
}

pub struct DependencyResolver;

impl DependencyResolver {
    pub fn new() -> Self { Self }

    pub fn resolve(&self, language: &str, framework: Option<&str>) -> Result<Vec<super::GeneratedFile>> {
        let files = match language {
            "rust" => self.resolve_rust(framework),
            "typescript" | "javascript" => self.resolve_typescript(framework),
            "python" => self.resolve_python(framework),
            "golang" => self.resolve_golang(framework),
            "java" => self.resolve_java(framework),
            "swift" => self.resolve_swift(),
            _ => Ok(Vec::new()),
        };

        files.map(|deps| deps.into_iter().map(|d| super::GeneratedFile {
            path: d.filename.into(),
            content: d.content,
            language: "text".into(),
            description: "依赖配置".into(),
        }).collect())
    }

    // ── Rust ──────────────────────────────────────────────────

    fn resolve_rust(&self, framework: Option<&str>) -> Result<Vec<DependencyFile>> {
        let mut deps = Vec::new();

        // Base deps
        deps.push(Dependency { name: "anyhow".into(), version: "1".into(), dev: false, optional: false, description: "错误处理" });
        deps.push(Dependency { name: "serde".into(), version: "1".into(), dev: false, optional: false, description: "序列化" });
        deps.push(Dependency { name: "serde_json".into(), version: "1".into(), dev: false, optional: false, description: "JSON 序列化" });
        deps.push(Dependency { name: "tokio".into(), version: "1".into(), dev: false, optional: false, description: "异步运行时" });
        deps.push(Dependency { name: "tracing".into(), version: "0.1".into(), dev: false, optional: false, description: "结构化日志" });
        deps.push(Dependency { name: "tracing-subscriber".into(), version: "0.3".into(), dev: false, optional: false, description: "日志格式" });
        deps.push(Dependency { name: "clap".into(), version: "4".into(), dev: false, optional: false, description: "CLI 参数解析" });
        deps.push(Dependency { name: "thiserror".into(), version: "1".into(), dev: false, optional: false, description: "错误类型" });
        deps.push(Dependency { name: "chrono".into(), version: "0.4".into(), dev: false, optional: false, description: "时间处理" });
        deps.push(Dependency { name: "tempfile".into(), version: "3".into(), dev: true, optional: false, description: "测试临时文件" });

        // Framework deps
        if framework == Some("axum") {
            deps.push(Dependency { name: "axum".into(), version: "0.7".into(), dev: false, optional: false, description: "Web 框架" });
            deps.push(Dependency { name: "tower".into(), version: "0.4".into(), dev: false, optional: false, description: "中间件" });
            deps.push(Dependency { name: "tower-http".into(), version: "0.5".into(), dev: false, optional: false, description: "HTTP 中间件" });
            deps.push(Dependency { name: "sqlx".into(), version: "0.7".into(), dev: false, optional: false, description: "数据库" });
        } else if framework == Some("actix-web") {
            deps.push(Dependency { name: "actix-web".into(), version: "4".into(), dev: false, optional: false, description: "Web 框架" });
            deps.push(Dependency { name: "sqlx".into(), version: "0.7".into(), dev: false, optional: false, description: "数据库" });
        } else if framework == Some("tauri") {
            deps.push(Dependency { name: "tauri".into(), version: "2".into(), dev: false, optional: false, description: "桌面框架" });
        }

        Ok(vec![self.render_cargo_toml(&deps)])
    }

    fn render_cargo_toml(&self, deps: &[Dependency]) -> DependencyFile {
        let mut runtime: Vec<&Dependency> = deps.iter().filter(|d| !d.dev).collect();
        let dev_deps: Vec<&Dependency> = deps.iter().filter(|d| d.dev).collect();

        let mut lines = vec![
            "# Generated by ACoder".into(),
            "[package]".into(),
            "name = \"generated\"".into(),
            "version = \"0.1.0\"".into(),
            "edition = \"2021\"".into(),
            "".into(),
            "[lib]".into(),
        ];

        if !runtime.is_empty() {
            lines.push("".into());
            lines.push("[dependencies]".into());
            for dep in runtime {
                lines.push(format!("{} = \"{}\"", dep.name, dep.version));
            }
        }

        if !dev_deps.is_empty() {
            lines.push("".into());
            lines.push("[dev-dependencies]".into());
            for dep in dev_deps {
                lines.push(format!("{} = \"{}\"", dep.name, dep.version));
            }
        }

        lines.push("".into());
        lines.push("[features]".into());
        lines.push("default = []".into());

        DependencyFile {
            filename: "Cargo.toml",
            content: lines.join("\n"),
        }
    }

    // ── TypeScript ────────────────────────────────────────────

    fn resolve_typescript(&self, framework: Option<&str>) -> Result<Vec<DependencyFile>> {
        let mut files = Vec::new();
        let deps = match framework {
            Some("react") | Some("nextjs") => self.ts_react_deps(),
            Some("vue") | Some("nuxt") => self.ts_vue_deps(),
            Some("express") => self.ts_express_deps(),
            _ => self.ts_react_deps(),
        };

        files.push(self.render_package_json(&deps));

        files.push(DependencyFile {
            filename: "vite.config.ts",
            content: "import { defineConfig } from 'vite'\nimport react from '@vitejs/plugin-react'\n\nexport default defineConfig({\n  plugins: [react()],\n  server: { port: 3000 },\n})\n".into(),
        });

        files.push(DependencyFile {
            filename: "tsconfig.json",
            content: "{
  \"compilerOptions\": {
    \"target\": \"ES2020\",
    \"lib\": [\"ES2020\", \"DOM\", \"DOM.Iterable\"],
    \"module\": \"ESNext\",
    \"skipLibCheck\": true,
    \"moduleResolution\": \"bundler\",
    \"allowImportingTsExtensions\": true,
    \"resolveJsonModule\": true,
    \"isolatedModules\": true,
    \"noEmit\": true,
    \"jsx\": \"react-jsx\",
    \"strict\": true,
    \"noUnusedLocals\": true,
    \"noFallthroughCasesInSwitch\": true
  },
  \"include\": [\"src\"]
}
".into(),
        });

        files.push(DependencyFile {
            filename: ".gitignore",
            content: "node_modules\ndist\n.env\n*.log\n".into(),
        });

        Ok(files)
    }

    fn ts_base_deps(&self) -> Vec<Dependency> {
        vec![
            Dependency { name: "typescript".into(), version: "^5.3.0".into(), dev: true, optional: false, description: "TypeScript" },
            Dependency { name: "vitest".into(), version: "^1.2.0".into(), dev: true, optional: false, description: "测试框架" },
            Dependency { name: "@types/node".into(), version: "^20.0.0".into(), dev: true, optional: false, description: "Node 类型" },
            Dependency { name: "zod".into(), version: "^3.22.0".into(), dev: false, optional: false, description: "类型验证" },
        ]
    }

    fn ts_react_deps(&self) -> Vec<Dependency> {
        let mut deps = self.ts_base_deps();
        deps.push(Dependency { name: "react".into(), version: "^18.2.0".into(), dev: false, optional: false, description: "UI 库" });
        deps.push(Dependency { name: "react-dom".into(), version: "^18.2.0".into(), dev: false, optional: false, description: "React DOM" });
        deps.push(Dependency { name: "@vitejs/plugin-react".into(), version: "^4.2.0".into(), dev: true, optional: false, description: "Vite 插件" });
        deps.push(Dependency { name: "vite".into(), version: "^5.0.0".into(), dev: true, optional: false, description: "构建工具" });
        deps.push(Dependency { name: "axios".into(), version: "^1.6.0".into(), dev: false, optional: false, description: "HTTP 客户端" });
        deps
    }

    fn ts_vue_deps(&self) -> Vec<Dependency> {
        let mut deps = self.ts_base_deps();
        deps.push(Dependency { name: "vue".into(), version: "^3.4.0".into(), dev: false, optional: false, description: "UI 库" });
        deps.push(Dependency { name: "vite".into(), version: "^5.0.0".into(), dev: true, optional: false, description: "构建工具" });
        deps.push(Dependency { name: "@vitejs/plugin-vue".into(), version: "^5.0.0".into(), dev: true, optional: false, description: "Vite 插件" });
        deps.push(Dependency { name: "axios".into(), version: "^1.6.0".into(), dev: false, optional: false, description: "HTTP 客户端" });
        deps
    }

    fn ts_express_deps(&self) -> Vec<Dependency> {
        let mut deps = self.ts_base_deps();
        deps.push(Dependency { name: "express".into(), version: "^4.18.0".into(), dev: false, optional: false, description: "Web 框架" });
        deps.push(Dependency { name: "@types/express".into(), version: "^4.17.0".into(), dev: true, optional: false, description: "Express 类型" });
        deps.push(Dependency { name: "cors".into(), version: "^2.8.0".into(), dev: false, optional: false, description: "跨域" });
        deps.push(Dependency { name: "dotenv".into(), version: "^16.3.0".into(), dev: false, optional: false, description: "环境变量" });
        deps
    }

    fn render_package_json(&self, deps: &[Dependency]) -> DependencyFile {
        let runtime: Vec<&Dependency> = deps.iter().filter(|d| !d.dev).collect();
        let dev: Vec<&Dependency> = deps.iter().filter(|d| d.dev).collect();

        let runtime_lines: Vec<String> = runtime.iter().map(|d| {
            format!("    \"{}\": \"{}\"", d.name, d.version)
        }).collect();
        let dev_lines: Vec<String> = dev.iter().map(|d| {
            format!("    \"{}\": \"{}\"", d.name, d.version)
        }).collect();

        let content = format!(
            "{{\n  \"name\": \"generated\",\n  \"version\": \"0.1.0\",\n  \"type\": \"module\",\n  \"scripts\": {{\n    \"dev\": \"vite\",\n    \"build\": \"tsc && vite build\",\n    \"preview\": \"vite preview\",\n    \"test\": \"vitest\"\n  }},\n  \"dependencies\": {{\n{}\n  }},\n  \"devDependencies\": {{\n{}\n  }}\n}}",
            runtime_lines.join(",\n"),
            dev_lines.join(",\n")
        );

        DependencyFile { filename: "package.json", content }
    }

    // ── Python ───────────────────────────────────────────────

    fn resolve_python(&self, framework: Option<&str>) -> Result<Vec<DependencyFile>> {
        let deps = match framework {
            Some("fastapi") => self.py_fastapi_deps(),
            Some("django") => self.py_django_deps(),
            Some("flask") => self.py_flask_deps(),
            _ => self.py_fastapi_deps(),
        };

        let mut files = Vec::new();

        let req_lines: Vec<String> = deps.iter()
            .filter(|d| !d.dev)
            .map(|d| format!("{}=={}", d.name, d.version))
            .collect();

        files.push(DependencyFile {
            filename: "requirements.txt",
            content: format!("# Generated by ACoder\n# Runtime dependencies\n{}\n", req_lines.join("\n")),
        });

        files.push(DependencyFile {
            filename: "pyproject.toml",
            content: "[project]\nname = \"generated\"\nversion = \"0.1.0\"\nrequires-python = \">=3.10\"\ndependencies = []\n\n[tool.pytest.ini_options]\ntestpaths = [\"tests\"]\n\n[tool.black]\nline-length = 100\n".into(),
        });

        files.push(DependencyFile {
            filename: ".gitignore",
            content: "__pycache__\n*.pyc\n.venv\n.env\n*.egg-info\ndist\nbuild\n".into(),
        });

        Ok(files)
    }

    fn py_fastapi_deps(&self) -> Vec<Dependency> {
        vec![
            Dependency { name: "fastapi".into(), version: "0.109.0".into(), dev: false, optional: false, description: "Web 框架" },
            Dependency { name: "uvicorn".into(), version: "0.27.0".into(), dev: false, optional: false, description: "ASGI 服务器" },
            Dependency { name: "pydantic".into(), version: "2.5.0".into(), dev: false, optional: false, description: "数据验证" },
            Dependency { name: "sqlalchemy".into(), version: "2.0.0".into(), dev: false, optional: false, description: "ORM" },
            Dependency { name: "pytest".into(), version: "7.4.0".into(), dev: true, optional: false, description: "测试框架" },
        ]
    }

    fn py_django_deps(&self) -> Vec<Dependency> {
        vec![
            Dependency { name: "django".into(), version: "5.0.0".into(), dev: false, optional: false, description: "Web 框架" },
            Dependency { name: "djangorestframework".into(), version: "3.14.0".into(), dev: false, optional: false, description: "REST API" },
            Dependency { name: "pytest".into(), version: "7.4.0".into(), dev: true, optional: false, description: "测试框架" },
        ]
    }

    fn py_flask_deps(&self) -> Vec<Dependency> {
        vec![
            Dependency { name: "flask".into(), version: "3.0.0".into(), dev: false, optional: false, description: "Web 框架" },
            Dependency { name: "pytest".into(), version: "7.4.0".into(), dev: true, optional: false, description: "测试框架" },
        ]
    }

    // ── Go ──────────────────────────────────────────────────

    fn resolve_golang(&self, _framework: Option<&str>) -> Result<Vec<DependencyFile>> {
        Ok(vec![DependencyFile {
            filename: "go.mod",
            content: "module generated\n\ngo 1.21\n\nrequire (\n\tgithub.com/gin-gonic/gin v1.9.1\n\tgithub.com/spf13/viper v1.18.0\n\tgithub.com/stretchr/testify v1.8.4\n)\n".into(),
        }])
    }

    // ── Java ───────────────────────────────────────────────

    fn resolve_java(&self, framework: Option<&str>) -> Result<Vec<DependencyFile>> {
        if framework == Some("spring-boot") {
            Ok(vec![DependencyFile {
                filename: "pom.xml",
                content: r#"<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.0</version>
    </parent>
    <groupId>com.example</groupId>
    <artifactId>generated</artifactId>
    <version>0.1.0</version>
    <properties>
        <java.version>17</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
"#.into(),
            }])
        } else {
            Ok(Vec::new())
        }
    }

    // ── Swift ─────────────────────────────────────────────

    fn resolve_swift(&self) -> Result<Vec<DependencyFile>> {
        Ok(vec![DependencyFile {
            filename: "Package.swift",
            content: "// swift-tools-version: 5.9\nimport PackageDescription\n\nlet package = Package(\n    name: \"Generated\",\n    platforms: [.macOS(.v13), .iOS(.v16)],\n    products: [.library(name: \"Generated\", targets: [\"Generated\"])],\n    dependencies: [],\n    targets: [\n        .target(name: \"Generated\", dependencies: []),\n        .testTarget(name: \"GeneratedTests\", dependencies: [\"Generated\"]),\n    ]\n)\n".into(),
        }])
    }
}

impl Default for DependencyResolver {
    fn default() -> Self { Self::new() }
}
